version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      employee-db:
        condition: service_healthy

  employee-db:
    image: postgres:16
    container_name: employee-db
    ports:
      - "5433:5432"  # Host:Container
    environment:
      POSTGRES_DB: employee-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  logs:
  db_data:
