server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: Inventory

  app:
    suppliers-service:
      host: localhost
      port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://inventory-db:3306/inventory-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      platform: mysql
      mode: always
      logging:
        enabled: true

  app:
    suppliers-service:
      host: suppliers-service
      port: 8080
