server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  application:
    name: Suppliers
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://suppliers-db/suppliers-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: mysql
      mode: always
      logging:
        enabled: true
