server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  application:
    name: Employee
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://employee-db:5432/employee-db  # Matches POSTGRES_DB
    username: user                                        # Matches POSTGRES_USER
    password: pwd                                         # Matches POSTGRES_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none                                      # Use 'none' if you're using schema.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:schema-postgres.sql
      data-locations: classpath:data-postgres.sql
      logging:
        enabled: true
