server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: reactive  # ✅ Fix: prevents Spring MVC conflict

  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: suppliers-service
          uri: http://suppliers-service:8080
          predicates:
            - Path=/api/v1/suppliers/**
          methods:
            - GET
            - POST
            - PUT
            - DELETE

        - id: employee-service
          uri: http://employee-service:8080
          predicates:
            - Path=/api/v1/employees/**
          methods:
            - GET
            - POST
            - PUT
            - DELETE

        - id: inventory-service
          uri: http://inventory-service:8080
          predicates:
            - Path=/api/v1/inventories/**
          methods:
            - GET
            - POST
            - PUT
            - DELETE

        - id: sales-service
          uri: http://sales-service:8080
          predicates:
            - Path=/api/v1/sales/**
          methods:
            - GET
            - POST
            - PUT
            - DELETE

        - id: payment-service
          uri: http://payment-service:8080
          predicates:
            - Path=/api/v1/payments/**
          methods:
            - GET
            - POST
            - PUT
            - DELETE

logging:
  level:
    root: INFO
    com.champsoft: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker

app:
  suppliers-service:
    host: suppliers-service
    port: 8080
  employee-service:
    host: employee-service
    port: 8080
  inventory-service:
    host: inventory-service
    port: 8080
  sales-service:
    host: sales-service
    port: 8080
  payment-service:
    host: payment-service
    port: 8080
