server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

payment-service:
  base-url: http://localhost:8080/api/v1/payments

---
spring:
  application:
    name: Sales
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://sales-db:3306/sales-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      platform: mysql
      mode: always
      logging:
        enabled: true

app:
  gateway:
    base-url: http://api-gateway:8080/api/v1

# ✅ Correct payment-service base-url for Docker
payment-service:
  base-url: http://payment-service:8080/api/v1/payments
