# Default profile (for local development)
server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  gateway:
    base-url: http://localhost:8080/api/v1

---

# Docker profile (used in containers)
spring:
  application:
    name: Sales
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://sales-db:3306/sales-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      platform: mysql
      mode: always
      logging:
        enabled: true

app:
  gateway:
    base-url: http://api-gateway-service:8080/api/v1  # ✅ Fixed here
  payment:
    base-url: http://payment-service:8080/api/v1
  supplier:
    base-url: http://suppliers-service:8080/api/v1
  inventory:
    base-url: http://inventory-service:8080/api/v1
